	ALTER TABLE EMP
		DROP
			CONSTRAINT FK_DEPT_TO_EMP
			CASCADE;

	ALTER TABLE DEPT
		DROP
			CONSTRAINT FK_EMP_TO_DEPT
			CASCADE;

	ALTER TABLE ATTEND
		DROP
			CONSTRAINT FK_EMP_TO_ATTEND
			CASCADE;

	ALTER TABLE OFF
		DROP
			CONSTRAINT FK_EMP_TO_OFF
			CASCADE;

	ALTER TABLE BOARD
		DROP
			CONSTRAINT FK_EMP_TO_BOARD
			CASCADE;

	ALTER TABLE SCHEDULE
		DROP
			CONSTRAINT FK_DEPT_TO_SCHEDULE
			CASCADE;

	ALTER TABLE EMP
		DROP
			UNIQUE (
				EMAIL
			)
			CASCADE
			KEEP INDEX;

	ALTER TABLE EMP
		DROP
			PRIMARY KEY
			CASCADE
			KEEP INDEX;

	ALTER TABLE DEPT
		DROP
			PRIMARY KEY
			CASCADE
			KEEP INDEX;

	ALTER TABLE ATTEND
		DROP
			PRIMARY KEY
			CASCADE
			KEEP INDEX;

	ALTER TABLE OFF
		DROP
			PRIMARY KEY
			CASCADE
			KEEP INDEX;

	ALTER TABLE BOARD
		DROP
			PRIMARY KEY
			CASCADE
			KEEP INDEX;

	ALTER TABLE SCHEDULE
		DROP
			PRIMARY KEY
			CASCADE
			KEEP INDEX;

	/* 사원 */
	DROP TABLE EMP 
		CASCADE CONSTRAINTS;

	/* 부서 */
	DROP TABLE DEPT 
		CASCADE CONSTRAINTS;

	/* 근태 */
	DROP TABLE ATTEND 
		CASCADE CONSTRAINTS;

	/* 휴가 */
	DROP TABLE OFF 
		CASCADE CONSTRAINTS;

	/* 게시글 */
	DROP TABLE BOARD 
		CASCADE CONSTRAINTS;

	/* 일정 */
	DROP TABLE SCHEDULE 
		CASCADE CONSTRAINTS;

	/* 사원 */
	CREATE TABLE EMP (
		EMPNO NUMBER(4) GENERATED ALWAYS AS IDENTITY(START WITH 1001 INCREMENT BY 1) PRIMARY KEY NOT NULL, /* 사원번호 */
		ENAME VARCHAR(50) NOT NULL, /* 이름 */
		PH VARCHAR(30) NOT NULL, /* 전화번호 */
		EMAIL VARCHAR(40) NOT NULL, /* 이메일 */
		HIREDATE DATE DEFAULT SYSDATE NOT NULL, /* 입사일 */
		BDAY DATE, /* 생년월일 */
		SAL NUMBER(9) DEFAULT 100 NOT NULL, /* 급여 */
		PWD VARCHAR(50) NOT NULL, /* 비밀번호 */
		DAYOFF NUMBER(2) DEFAULT 0 NOT NULL, /* 연차 */
		DEPTNO NUMBER(2) /* 부서번호 */
	);

	COMMENT ON TABLE EMP IS '사원';

	COMMENT ON COLUMN EMP.EMPNO IS '사원번호';

	COMMENT ON COLUMN EMP.ENAME IS '이름';

	COMMENT ON COLUMN EMP.PH IS '전화번호';

	COMMENT ON COLUMN EMP.EMAIL IS '이메일';

	COMMENT ON COLUMN EMP.HIREDATE IS '입사일';

	COMMENT ON COLUMN EMP.BDAY IS '생년월일';

	COMMENT ON COLUMN EMP.SAL IS '급여';

	COMMENT ON COLUMN EMP.PWD IS '비밀번호';

	COMMENT ON COLUMN EMP.DAYOFF IS '연차';

	COMMENT ON COLUMN EMP.DEPTNO IS '부서번호';

	-- ALTER TABLE EMP
	-- 	ADD
	-- 		CONSTRAINT PK_EMP
	-- 		PRIMARY KEY (
	-- 			EMPNO
	-- 		);

	ALTER TABLE EMP
		ADD
			CONSTRAINT UK_EMP
			UNIQUE (
				EMAIL
			);

	/* 부서 */
	CREATE TABLE DEPT (
		DEPTNO NUMBER(2) GENERATED ALWAYS AS IDENTITY(START WITH 10 INCREMENT BY 1) PRIMARY KEY NOT NULL, /* 부서번호 */
		DNAME VARCHAR(50) NOT NULL, /* 부서명 */
		DHEAD NUMBER(4) NOT NULL /* 부서장 */
	);

	COMMENT ON TABLE DEPT IS '부서';

	COMMENT ON COLUMN DEPT.DEPTNO IS '부서번호';

	COMMENT ON COLUMN DEPT.DNAME IS '부서명';

	COMMENT ON COLUMN DEPT.DHEAD IS '부서장';

	-- ALTER TABLE DEPT
	-- 	ADD
	-- 		CONSTRAINT PK_DEPT
	-- 		PRIMARY KEY (
	-- 			DEPTNO
	-- 		);

	/* 근태 */
	CREATE TABLE ATTEND (
		ATTNO NUMBER(7) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL, /* 근태번호 */
		EMPNO NUMBER(4) NOT NULL, /* 사원번호 */
		A_START DATE DEFAULT SYSDATE NOT NULL, /* 출근일시 */
		A_END DATE /* 퇴근일시 */
	);

	COMMENT ON TABLE ATTEND IS '근태';

	COMMENT ON COLUMN ATTEND.ATTNO IS '근태번호';

	COMMENT ON COLUMN ATTEND.EMPNO IS '사원번호';

	COMMENT ON COLUMN ATTEND.A_START IS '출근일시';

	COMMENT ON COLUMN ATTEND.A_END IS '퇴근일시';

	-- ALTER TABLE ATTEND
	-- 	ADD
	-- 		CONSTRAINT PK_ATTEND
	-- 		PRIMARY KEY (
	-- 			ATTNO
	-- 		);

	/* 휴가 */
	CREATE TABLE OFF (
		EMPNO NUMBER(4) NOT NULL, /* 사원번호 */
		O_START DATE NOT NULL, /* 시작일 */
		O_END DATE NOT NULL, /* 종료일 */
		ACCEPTED CHAR(1) DEFAULT 'N' NOT NULL /* 결재여부 */
	);

	COMMENT ON TABLE OFF IS '휴가';

	COMMENT ON COLUMN OFF.EMPNO IS '사원번호';

	COMMENT ON COLUMN OFF.O_START IS '시작일';

	COMMENT ON COLUMN OFF.O_END IS '종료일';

	COMMENT ON COLUMN OFF.ACCEPTED IS '결재여부';

	ALTER TABLE OFF
		ADD
			CONSTRAINT PK_OFF
			PRIMARY KEY (
				EMPNO,
				O_START
			);

	/* 게시글 */
	CREATE TABLE BOARD (
		B_NO NUMBER(7) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL, /* 글번호 */
		EMPNO NUMBER(4) NOT NULL, /* 사원번호 */
		B_BODY LONG NOT NULL, /* 내용 */
		WDATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL /* 작성일시 */
	);

	COMMENT ON TABLE BOARD IS '게시글';

	COMMENT ON COLUMN BOARD.B_NO IS '글번호';

	COMMENT ON COLUMN BOARD.EMPNO IS '사원번호';

	COMMENT ON COLUMN BOARD.B_BODY IS '내용';

	COMMENT ON COLUMN BOARD.WDATE IS '작성일시';

	-- ALTER TABLE BOARD
	-- 	ADD
	-- 		CONSTRAINT PK_BOARD
	-- 		PRIMARY KEY (
	-- 			B_NO
	-- 		);

	/* 일정 */
	CREATE TABLE SCHEDULE (
		S_NO NUMBER(6) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL, /* 일정번호 */
		DEPTNO NUMBER(2), /* 부서번호 */
		S_BODY LONG NOT NULL, /* 내용 */
		S_START DATE DEFAULT SYSDATE NOT NULL, /* 시작일시 */
		S_END DATE /* 종료일시 */
	);

	COMMENT ON TABLE SCHEDULE IS '일정';

	COMMENT ON COLUMN SCHEDULE.S_NO IS '일정번호';

	COMMENT ON COLUMN SCHEDULE.DEPTNO IS '부서번호';

	COMMENT ON COLUMN SCHEDULE.S_BODY IS '내용';

	COMMENT ON COLUMN SCHEDULE.S_START IS '시작일시';

	COMMENT ON COLUMN SCHEDULE.S_END IS '종료일시';

	-- ALTER TABLE SCHEDULE
	-- 	ADD
	-- 		CONSTRAINT PK_SCHEDULE
	-- 		PRIMARY KEY (
	-- 			S_NO
	-- 		);

	ALTER TABLE EMP
		ADD
			CONSTRAINT FK_DEPT_TO_EMP
			FOREIGN KEY (
				DEPTNO
			)
			REFERENCES DEPT (
				DEPTNO
			);

	ALTER TABLE DEPT
		ADD
			CONSTRAINT FK_EMP_TO_DEPT
			FOREIGN KEY (
				DHEAD
			)
			REFERENCES EMP (
				EMPNO
			);

	ALTER TABLE ATTEND
		ADD
			CONSTRAINT FK_EMP_TO_ATTEND
			FOREIGN KEY (
				EMPNO
			)
			REFERENCES EMP (
				EMPNO
			);

	ALTER TABLE OFF
		ADD
			CONSTRAINT FK_EMP_TO_OFF
			FOREIGN KEY (
				EMPNO
			)
			REFERENCES EMP (
				EMPNO
			);

	ALTER TABLE BOARD
		ADD
			CONSTRAINT FK_EMP_TO_BOARD
			FOREIGN KEY (
				EMPNO
			)
			REFERENCES EMP (
				EMPNO
			);

	ALTER TABLE SCHEDULE
		ADD
			CONSTRAINT FK_DEPT_TO_SCHEDULE
			FOREIGN KEY (
				DEPTNO
			)
			REFERENCES DEPT (
				DEPTNO
			);