/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proj;

import javax.swing.JFrame;

public class App extends JFrame {
    public static void main(String[] args) {
        LogUI lu = new LogUI();
        lu.init();
        lu.setUI();
    }

}